import jsPDF from "jspdf";

const NAVY: [number, number, number] = [27, 58, 140]; // #1B3A8C
const ORANGE: [number, number, number] = [244, 121, 32]; // #F47920
const TEXT: [number, number, number] = [33, 33, 33];
const MUTED: [number, number, number] = [110, 116, 130];
const BORDER: [number, number, number] = [220, 224, 230];

export interface PassportPdfInput {
  propertyId: string;
  address: string;
  yearBuilt?: number | null;
  healthScore?: number | null;
  systems?: { name: string; health: number; lastService?: string }[];
  documentsCount?: number;
  verifiedRecords?: number;
  govSourcesFound?: string[];
  welcomeNote?: string;
  sellerName?: string;
  referralCode?: string | null;
}

const SITE = "cominghomeiq.com";

function applyHeader(doc: jsPDF, address: string) {
  const pageW = doc.internal.pageSize.getWidth();
  doc.setFillColor(...NAVY);
  doc.rect(0, 0, pageW, 14, "F");
  // Logo mark
  doc.setFillColor(...ORANGE);
  doc.circle(10, 7, 3.2, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text("ComingHomeIQ", 16, 8.6);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.text("Home Passport — Powered by ComingHomeIQ", 16, 12);
  // Address top right (truncate)
  const addr = (address || "").length > 48 ? address.slice(0, 45) + "…" : address || "";
  doc.setFontSize(8);
  doc.text(addr, pageW - 8, 9, { align: "right" });
}

function applyFooter(doc: jsPDF, pageNum: number, totalPages: number) {
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  doc.setDrawColor(...BORDER);
  doc.setLineWidth(0.2);
  doc.line(8, pageH - 18, pageW - 8, pageH - 18);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(...MUTED);
  doc.text(`Generated by ComingHomeIQ — ${SITE}`, 8, pageH - 12);
  doc.text(`Generated ${new Date().toLocaleDateString()}`, 8, pageH - 8);
  doc.text(
    "Records sourced from FEMA, NOAA, EPA, USDA, Census Bureau, and owner-provided documentation.",
    8,
    pageH - 4,
  );
  doc.text(`Page ${pageNum} of ${totalPages}`, pageW - 8, pageH - 8, { align: "right" });
}

export async function generatePassportPdf(data: PassportPdfInput): Promise<void> {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();

  // ===== Page 1 — Overview =====
  applyHeader(doc, data.address);
  let y = 26;
  doc.setTextColor(...TEXT);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("Home Passport", 8, y);
  y += 7;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(...MUTED);
  doc.text(data.address || "Property", 8, y);
  if (data.yearBuilt) {
    y += 5;
    doc.text(`Built ${data.yearBuilt}`, 8, y);
  }

  y += 12;
  // Score box
  doc.setDrawColor(...BORDER);
  doc.roundedRect(8, y, pageW - 16, 28, 2, 2, "S");
  doc.setTextColor(...TEXT);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(28);
  const score = data.healthScore != null ? `${data.healthScore}` : "—";
  doc.text(score, 16, y + 19);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...MUTED);
  doc.text("Home IQ Score", 16, y + 24);
  doc.setFontSize(10);
  doc.setTextColor(...TEXT);
  doc.text(`Verified records: ${data.verifiedRecords ?? 0}`, 60, y + 11);
  doc.text(`Documents: ${data.documentsCount ?? 0}`, 60, y + 17);
  doc.text(`Systems: ${data.systems?.length ?? 0}`, 60, y + 23);
  if (data.govSourcesFound && data.govSourcesFound.length) {
    doc.text(`Gov sources: ${data.govSourcesFound.join(", ")}`, 110, y + 11, { maxWidth: pageW - 118 });
  }
  y += 38;

  // Systems table
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(...TEXT);
  doc.text("Systems Documented", 8, y);
  y += 5;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...MUTED);
  (data.systems ?? []).forEach((s) => {
    if (y > pageH - 28) {
      applyFooter(doc, doc.getNumberOfPages(), 0); // placeholder, fixed later
      doc.addPage();
      applyHeader(doc, data.address);
      y = 26;
    }
    doc.setTextColor(...TEXT);
    doc.text(s.name, 10, y);
    doc.setTextColor(...MUTED);
    doc.text(`${s.health}%`, 90, y);
    if (s.lastService) doc.text(`Last: ${s.lastService}`, 110, y);
    y += 6;
  });

  if (data.welcomeNote) {
    if (y > pageH - 60) {
      doc.addPage();
      applyHeader(doc, data.address);
      y = 26;
    }
    y += 6;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(...TEXT);
    doc.text("A Note From the Seller", 8, y);
    y += 5;
    doc.setFont("helvetica", "italic");
    doc.setFontSize(9.5);
    doc.setTextColor(...MUTED);
    const lines = doc.splitTextToSize(`"${data.welcomeNote}"`, pageW - 16);
    doc.text(lines, 8, y);
    y += lines.length * 5;
  }

  // ===== Last Page — CTA =====
  doc.addPage();
  doc.setFillColor(...NAVY);
  doc.rect(0, 0, pageW, pageH, "F");
  // Brand mark
  doc.setFillColor(...ORANGE);
  doc.circle(pageW / 2, 60, 7, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text("This home's record was built", pageW / 2, 85, { align: "center" });
  doc.text("with ComingHomeIQ.", pageW / 2, 95, { align: "center" });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  const body =
    "ComingHomeIQ is the free home intelligence platform that pulls permit history, flood zone data, warranty records, and maintenance history — everything in one permanent file.";
  const bodyLines = doc.splitTextToSize(body, pageW - 40);
  doc.text(bodyLines, pageW / 2, 112, { align: "center" });

  // Buyer claim CTA
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("If you're buying this home, claim this file and make it yours:", pageW / 2, 142, { align: "center" });
  doc.setFillColor(...ORANGE);
  doc.roundedRect(pageW / 2 - 70, 148, 140, 14, 3, 3, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(11);
  const claimUrl = `${SITE}/claim/${data.propertyId}`;
  doc.textWithLink(claimUrl, pageW / 2, 157, { align: "center", url: `https://${claimUrl}` });

  // Owner CTA
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(255, 255, 255);
  doc.text("If you want this for your own home:", pageW / 2, 180, { align: "center" });
  doc.setFont("helvetica", "normal");
  const refUrl = data.referralCode
    ? `${SITE}?ref=${data.referralCode}`
    : `${SITE}`;
  doc.setTextColor(...ORANGE);
  doc.textWithLink(refUrl, pageW / 2, 188, { align: "center", url: `https://${refUrl}` });

  // Independence statement
  doc.setFont("helvetica", "italic");
  doc.setFontSize(9);
  doc.setTextColor(210, 215, 225);
  const indep =
    "ComingHomeIQ is independent — not owned by an insurance company, warranty provider, or real estate brokerage.";
  const indepLines = doc.splitTextToSize(indep, pageW - 50);
  doc.text(indepLines, pageW / 2, pageH - 28, { align: "center" });

  // Apply header (light variant skipped on dark CTA page) — only footer shown elsewhere
  // Re-apply headers/footers across all pages with correct totals
  const total = doc.getNumberOfPages();
  for (let p = 1; p <= total; p++) {
    doc.setPage(p);
    if (p < total) {
      // header already drawn on creation; redraw to be safe, then footer
      // (do not redraw on CTA last page)
      applyFooter(doc, p, total);
    } else {
      // small footer with page number on CTA page in white
      const pageH2 = doc.internal.pageSize.getHeight();
      const pageW2 = doc.internal.pageSize.getWidth();
      doc.setFont("helvetica", "normal");
      doc.setFontSize(7.5);
      doc.setTextColor(210, 215, 225);
      doc.text(`Generated by ComingHomeIQ — ${SITE} · Generated ${new Date().toLocaleDateString()}`, 8, pageH2 - 6);
      doc.text(`Page ${p} of ${total}`, pageW2 - 8, pageH2 - 6, { align: "right" });
    }
  }

  const safeAddr = (data.address || "home").replace(/[^a-z0-9]+/gi, "-").slice(0, 40);
  doc.save(`HomePassport-${safeAddr}.pdf`);
}